### ISSUE TITLE
FAILURE in default 

### ISSUE THREAD

**Issue by thomasbnt** [Slimefun/discord-webhook#6]
`{ status: 'FAILURE', tests: [], coverage: 0, time: '0.000' }`

Hello i've got no tests but the Action show the push in Failure.. the embed is red and no logs about that.

![image](https://user-images.githubusercontent.com/14293805/83949662-73e70e00-a825-11ea-975b-96979d8fcd7c.png)

**Comment by TheBusyBiscuit** [comment]
Hi, can you please send the full actions log, your pom.xml (or a link to your GitHub repository) and maybe also a full screenshot of the entire embed?
It isn't really easy to make out much from that small section of the image.

**Comment by thomasbnt** [comment]
Yeah, I was going to do that to you. It's private source code.

```bash
2020-06-06T16:35:01.3033234Z     "site_admin": false,
2020-06-06T16:35:01.3033498Z     "starred_url": "https://api.github.com/users/thomasbnt/starred{/owner}{/repo}",
2020-06-06T16:35:01.3033796Z     "subscriptions_url": "https://api.github.com/users/thomasbnt/subscriptions",
2020-06-06T16:35:01.3034065Z     "type": "User",
2020-06-06T16:35:01.3034319Z     "url": "https://api.github.com/users/thomasbnt"
2020-06-06T16:35:01.3034575Z   }
2020-06-06T16:35:01.3034800Z }
2020-06-06T16:35:01.3035026Z Received 1/1 commits...
2020-06-06T16:35:01.3041508Z Running 'mvn test'...
2020-06-06T16:35:07.9960705Z [
2020-06-06T16:35:07.9964462Z I
2020-06-06T16:35:07.9967243Z N
2020-06-06T16:35:07.9970176Z F
2020-06-06T16:35:07.9973002Z O
2020-06-06T16:35:07.9975873Z ]
2020-06-06T16:35:07.9978711Z  
2020-06-06T16:35:07.9981568Z S
2020-06-06T16:35:07.9984349Z c
2020-06-06T16:35:07.9987128Z a
2020-06-06T16:35:07.9990798Z n
2020-06-06T16:35:07.9993443Z n
2020-06-06T16:35:07.9996204Z i
2020-06-06T16:35:07.9998351Z n
2020-06-06T16:35:08.0001125Z g
2020-06-06T16:35:08.0003938Z  
2020-06-06T16:35:08.0006608Z f
2020-06-06T16:35:08.0010740Z o
2020-06-06T16:35:08.0013516Z r
2020-06-06T16:35:08.0016162Z  
2020-06-06T16:35:08.0019007Z p
2020-06-06T16:35:08.0021543Z r
2020-06-06T16:35:08.0024233Z o
2020-06-06T16:35:08.0028145Z j
2020-06-06T16:35:08.0032817Z e
2020-06-06T16:35:08.0036493Z c
2020-06-06T16:35:08.0040237Z t
2020-06-06T16:35:08.0043985Z s
2020-06-06T16:35:08.0047672Z .
2020-06-06T16:35:08.0051611Z .
2020-06-06T16:35:08.0055426Z .
2020-06-06T16:35:08.0060244Z 
2020-06-06T16:35:08.0060341Z 
2020-06-06T16:35:08.1555920Z [INF
2020-06-06T16:35:08.1557249Z O] ----------
2020-06-06T16:35:08.1560346Z ----------
2020-06-06T16:35:08.1564032Z --------
2020-06-06T16:35:08.1566622Z --
2020-06-06T16:35:08.1567384Z --------
2020-06-06T16:35:08.1569661Z --
2020-06-06T16:35:08.1570505Z -------
2020-06-06T16:35:08.1572829Z --
2020-06-06T16:35:08.1573455Z -------
2020-06-06T16:35:08.1575629Z --
2020-06-06T16:35:08.1576310Z ------
2020-06-06T16:35:08.1578455Z --
2020-06-06T16:35:08.1579088Z -----
2020-06-06T16:35:08.1581324Z -
2020-06-06T16:35:08.1581776Z 
2020-06-06T16:35:08.1584001Z [I
2020-06-06T16:35:08.1584443Z NFO] 
2020-06-06T16:35:08.1586266Z BU
2020-06-06T16:35:08.1586711Z ILD 
2020-06-06T16:35:08.1597413Z FAILURE
2020-06-06T16:35:08.1598360Z [INFO] ------------------------------------------------------------------------
2020-06-06T16:35:08.1717487Z 
2020-06-06T16:35:08.1717708Z [
2020-06-06T16:35:08.1719398Z I
2020-06-06T16:35:08.1720597Z N
2020-06-06T16:35:08.1721936Z F
2020-06-06T16:35:08.1723196Z O
2020-06-06T16:35:08.1724537Z ]
2020-06-06T16:35:08.1725775Z  
2020-06-06T16:35:08.1727039Z T
2020-06-06T16:35:08.1728255Z o
2020-06-06T16:35:08.1729521Z t
2020-06-06T16:35:08.1731079Z a
2020-06-06T16:35:08.1732340Z l
2020-06-06T16:35:08.1788537Z  
2020-06-06T16:35:08.1792856Z t
2020-06-06T16:35:08.1800194Z i
2020-06-06T16:35:08.1800592Z m
2020-06-06T16:35:08.1800802Z e
2020-06-06T16:35:08.1801213Z :
2020-06-06T16:35:08.1801489Z  
2020-06-06T16:35:08.1801601Z  
2020-06-06T16:35:08.1801707Z 0
2020-06-06T16:35:08.1801815Z .
2020-06-06T16:35:08.1801904Z 2
2020-06-06T16:35:08.1802009Z 3
2020-06-06T16:35:08.1802115Z 4
2020-06-06T16:35:08.1802216Z  
2020-06-06T16:35:08.1802316Z s
2020-06-06T16:35:08.1802368Z 
2020-06-06T16:35:08.1802464Z 
2020-06-06T16:35:08.1802570Z [
2020-06-06T16:35:08.1802674Z I
2020-06-06T16:35:08.1802776Z N
2020-06-06T16:35:08.1802861Z F
2020-06-06T16:35:08.1802965Z O
2020-06-06T16:35:08.1803066Z ]
2020-06-06T16:35:08.1803166Z  
2020-06-06T16:35:08.1803272Z F
2020-06-06T16:35:08.1803372Z i
2020-06-06T16:35:08.1803472Z n
2020-06-06T16:35:08.1803559Z i
2020-06-06T16:35:08.1803660Z s
2020-06-06T16:35:08.1803760Z h
2020-06-06T16:35:08.1803884Z e
2020-06-06T16:35:08.1803987Z d
2020-06-06T16:35:08.1804088Z  
2020-06-06T16:35:08.1804190Z a
2020-06-06T16:35:08.1804276Z t
2020-06-06T16:35:08.1804378Z :
2020-06-06T16:35:08.1804482Z  
2020-06-06T16:35:08.1804584Z 2
2020-06-06T16:35:08.1804692Z 0
2020-06-06T16:35:08.1804793Z 2
2020-06-06T16:35:08.1804895Z 0
2020-06-06T16:35:08.1805546Z -
2020-06-06T16:35:08.1805660Z 0
2020-06-06T16:35:08.1805764Z 6
2020-06-06T16:35:08.1806009Z -
2020-06-06T16:35:08.1806119Z 0
2020-06-06T16:35:08.1806221Z 6
2020-06-06T16:35:08.1806327Z T
2020-06-06T16:35:08.1806414Z 1
2020-06-06T16:35:08.1806517Z 6
2020-06-06T16:35:08.1806620Z :
2020-06-06T16:35:08.1806724Z 3
2020-06-06T16:35:08.1806827Z 5
2020-06-06T16:35:08.1806930Z :
2020-06-06T16:35:08.1807016Z 0
2020-06-06T16:35:08.1807120Z 8
2020-06-06T16:35:08.1807223Z Z
2020-06-06T16:35:08.1807291Z 
2020-06-06T16:35:08.1807340Z 
2020-06-06T16:35:08.1807463Z [
2020-06-06T16:35:08.1807565Z I
2020-06-06T16:35:08.1808507Z N
2020-06-06T16:35:08.1810901Z F
2020-06-06T16:35:08.1813059Z O
2020-06-06T16:35:08.1815118Z ]
2020-06-06T16:35:08.1817237Z  
2020-06-06T16:35:08.1819623Z -
2020-06-06T16:35:08.1821641Z -
2020-06-06T16:35:08.1823685Z -
2020-06-06T16:35:08.1825782Z -
2020-06-06T16:35:08.1827862Z -
2020-06-06T16:35:08.1830661Z -
2020-06-06T16:35:08.1832769Z -
2020-06-06T16:35:08.1834906Z -
2020-06-06T16:35:08.1836975Z -
2020-06-06T16:35:08.1839080Z -
2020-06-06T16:35:08.1841941Z -
2020-06-06T16:35:08.1844600Z -
2020-06-06T16:35:08.1847346Z -
2020-06-06T16:35:08.1851140Z -
2020-06-06T16:35:08.1856348Z -
2020-06-06T16:35:08.1859976Z -
2020-06-06T16:35:08.1863802Z -
2020-06-06T16:35:08.1867709Z -
2020-06-06T16:35:08.1871432Z -
2020-06-06T16:35:08.1874509Z -
2020-06-06T16:35:08.1877765Z -
2020-06-06T16:35:08.1880802Z -
2020-06-06T16:35:08.1883914Z -
2020-06-06T16:35:08.1886939Z -
2020-06-06T16:35:08.1890278Z -
2020-06-06T16:35:08.1892692Z -
2020-06-06T16:35:08.1895847Z -
2020-06-06T16:35:08.1898646Z -
2020-06-06T16:35:08.1900985Z -
2020-06-06T16:35:08.1903344Z -
2020-06-06T16:35:08.1906411Z -
2020-06-06T16:35:08.1908913Z -
2020-06-06T16:35:08.1911347Z -
2020-06-06T16:35:08.1913803Z -
2020-06-06T16:35:08.1916564Z -
2020-06-06T16:35:08.1919432Z -
2020-06-06T16:35:08.1921846Z -
2020-06-06T16:35:08.1924356Z -
2020-06-06T16:35:08.1926737Z -
2020-06-06T16:35:08.1929224Z -
2020-06-06T16:35:08.1932168Z -
2020-06-06T16:35:08.1934642Z -
2020-06-06T16:35:08.1937100Z -
2020-06-06T16:35:08.1938631Z -
2020-06-06T16:35:08.1941201Z -
2020-06-06T16:35:08.1943574Z -
2020-06-06T16:35:08.1946359Z -
2020-06-06T16:35:08.1948768Z -
2020-06-06T16:35:08.1957413Z ------------------------
2020-06-06T16:35:08.1957524Z 
2020-06-06T16:35:08.2048712Z [
2020-06-06T16:35:08.2048862Z E
2020-06-06T16:35:08.2048970Z R
2020-06-06T16:35:08.2050943Z R
2020-06-06T16:35:08.2051042Z O
2020-06-06T16:35:08.2052955Z R
2020-06-06T16:35:08.2053069Z ]
2020-06-06T16:35:08.2059873Z  
2020-06-06T16:35:08.2059998Z The goal you 
2020-06-06T16:35:08.2123537Z s
2020-06-06T16:35:08.2124703Z p
2020-06-06T16:35:08.2125878Z e
2020-06-06T16:35:08.2128522Z c
2020-06-06T16:35:08.2128649Z i
2020-06-06T16:35:08.2128771Z f
2020-06-06T16:35:08.2128891Z i
2020-06-06T16:35:08.2129266Z e
2020-06-06T16:35:08.2130197Z d
2020-06-06T16:35:08.2130954Z  
2020-06-06T16:35:08.2131741Z r
2020-06-06T16:35:08.2132863Z e
2020-06-06T16:35:08.2153233Z quires a project to execute but there is no POM in this directory (/home/runner/work/-/-). Please verify you invoked Maven from the correct directory. -> [Help 1]
2020-06-06T16:35:08.2153446Z [ERROR] 
2020-06-06T16:35:08.2153818Z [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
2020-06-06T16:35:08.2153953Z [E
2020-06-06T16:35:08.2154082Z R
2020-06-06T16:35:08.2154203Z R
2020-06-06T16:35:08.2157386Z O
2020-06-06T16:35:08.2157523Z R
2020-06-06T16:35:08.2157642Z ]
2020-06-06T16:35:08.2157759Z  
2020-06-06T16:35:08.2157876Z R
2020-06-06T16:35:08.2157976Z e
2020-06-06T16:35:08.2165469Z -
2020-06-06T16:35:08.2165606Z r
2020-06-06T16:35:08.2165724Z u
2020-06-06T16:35:08.2167333Z n
2020-06-06T16:35:08.2167623Z  
2020-06-06T16:35:08.2167746Z M
2020-06-06T16:35:08.2167848Z a
2020-06-06T16:35:08.2167968Z v
2020-06-06T16:35:08.2168090Z e
2020-06-06T16:35:08.2168922Z n
2020-06-06T16:35:08.2169200Z  
2020-06-06T16:35:08.2169331Z u
2020-06-06T16:35:08.2169473Z s
2020-06-06T16:35:08.2169573Z i
2020-06-06T16:35:08.2169697Z n
2020-06-06T16:35:08.2170693Z g
2020-06-06T16:35:08.2170830Z  
2020-06-06T16:35:08.2170965Z t
2020-06-06T16:35:08.2184924Z he -X switch to enable full debug logging.
2020-06-06T16:35:08.2185658Z [ERROR] 
2020-06-06T16:35:08.2185816Z [ERROR] For more information about the errors and possible solutions, please read the following articles:
2020-06-06T16:35:08.2186320Z [ERROR] [Help 1] http://cwiki.apache.or
2020-06-06T16:35:08.2186454Z g
2020-06-06T16:35:08.2186581Z /
2020-06-06T16:35:08.2187350Z c
2020-06-06T16:35:08.2187790Z o
2020-06-06T16:35:08.2187920Z n
2020-06-06T16:35:08.2188042Z f
2020-06-06T16:35:08.2188171Z l
2020-06-06T16:35:08.2188523Z u
2020-06-06T16:35:08.2189341Z e
2020-06-06T16:35:08.2190193Z n
2020-06-06T16:35:08.2190875Z c
2020-06-06T16:35:08.2191619Z e
2020-06-06T16:35:08.2192383Z /
2020-06-06T16:35:08.2193127Z d
2020-06-06T16:35:08.2193812Z i
2020-06-06T16:35:08.2208748Z splay/MAVEN/MissingProjectException
2020-06-06T16:35:08.2209085Z 
2020-06-06T16:35:08.2347164Z Aggregating test results...
2020-06-06T16:35:08.2382848Z ChildProcessError: `mvn test -B` failed with code 1
2020-06-06T16:35:08.2383817Z     at ChildProcess.<anonymous> (/home/runner/work/_actions/thomasbnt/discord-webhook/master/node_modules/child-process-promise/lib/index.js:132:23)
2020-06-06T16:35:08.2384318Z     at ChildProcess.emit (events.js:210:5)
2020-06-06T16:35:08.2384674Z     at maybeClose (internal/child_process.js:1021:16)
2020-06-06T16:35:08.2385016Z     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5) {
2020-06-06T16:35:08.2385579Z   name: 'ChildProcessError',
2020-06-06T16:35:08.2385966Z   code: 1,
2020-06-06T16:35:08.2386284Z   childProcess: ChildProcess {
2020-06-06T16:35:08.2387039Z     _events: [Object: null prototype] { error: [Function], close: [Function] },
2020-06-06T16:35:08.2387454Z     _eventsCount: 2,
2020-06-06T16:35:08.2387788Z     _maxListeners: undefined,
2020-06-06T16:35:08.2388120Z     _closesNeeded: 3,
2020-06-06T16:35:08.2388440Z     _closesGot: 3,
2020-06-06T16:35:08.2388754Z     connected: false,
2020-06-06T16:35:08.2389051Z     signalCode: null,
2020-06-06T16:35:08.2389373Z     exitCode: 1,
2020-06-06T16:35:08.2389686Z     killed: false,
2020-06-06T16:35:08.2390250Z     spawnfile: '/bin/sh',
2020-06-06T16:35:08.2391090Z     _handle: null,
2020-06-06T16:35:08.2391742Z     spawnargs: [ '/bin/sh', '-c', 'mvn test -B' ],
2020-06-06T16:35:08.2392153Z     pid: 2852,
2020-06-06T16:35:08.2392481Z     stdin: Socket {
2020-06-06T16:35:08.2392897Z       connecting: false,
2020-06-06T16:35:08.2393153Z       _hadError: false,
2020-06-06T16:35:08.2393569Z       _parent: null,
2020-06-06T16:35:08.2393713Z       _host: null,
2020-06-06T16:35:08.2393870Z       _readableState: [ReadableState],
2020-06-06T16:35:08.2394089Z       readable: false,
2020-06-06T16:35:08.2394227Z       _events: [Object: null prototype],
2020-06-06T16:35:08.2394358Z       _eventsCount: 1,
2020-06-06T16:35:08.2394799Z       _maxListeners: undefined,
2020-06-06T16:35:08.2394959Z       _writableState: [WritableState],
2020-06-06T16:35:08.2395089Z       writable: false,
2020-06-06T16:35:08.2395218Z       allowHalfOpen: false,
2020-06-06T16:35:08.2395346Z       _sockname: null,
2020-06-06T16:35:08.2395457Z       _pendingData: null,
2020-06-06T16:35:08.2395977Z       _pendingEncoding: '',
2020-06-06T16:35:08.2396116Z       server: null,
2020-06-06T16:35:08.2396242Z       _server: null,
2020-06-06T16:35:08.2396369Z       [Symbol(asyncId)]: 7,
2020-06-06T16:35:08.2396499Z       [Symbol(kHandle)]: null,
2020-06-06T16:35:08.2396629Z       [Symbol(lastWriteQueueSize)]: 0,
2020-06-06T16:35:08.2396759Z       [Symbol(timeout)]: null,
2020-06-06T16:35:08.2396869Z       [Symbol(kBuffer)]: null,
2020-06-06T16:35:08.2397011Z       [Symbol(kBufferCb)]: null,
2020-06-06T16:35:08.2397139Z       [Symbol(kBufferGen)]: null,
2020-06-06T16:35:08.2397268Z       [Symbol(kBytesRead)]: 0,
2020-06-06T16:35:08.2397399Z       [Symbol(kBytesWritten)]: 0
2020-06-06T16:35:08.2398301Z     },
2020-06-06T16:35:08.2398434Z     stdout: Socket {
2020-06-06T16:35:08.2398563Z       connecting: false,
2020-06-06T16:35:08.2398674Z       _hadError: false,
2020-06-06T16:35:08.2398805Z       _parent: null,
2020-06-06T16:35:08.2398934Z       _host: null,
2020-06-06T16:35:08.2399059Z       _readableState: [ReadableState],
2020-06-06T16:35:08.2399302Z       readable: false,
2020-06-06T16:35:08.2399435Z       _events: [Object: null prototype],
2020-06-06T16:35:08.2399565Z       _eventsCount: 3,
2020-06-06T16:35:08.2399692Z       _maxListeners: undefined,
2020-06-06T16:35:08.2399808Z       _writableState: [WritableState],
2020-06-06T16:35:08.2399939Z       writable: false,
2020-06-06T16:35:08.2400068Z       allowHalfOpen: false,
2020-06-06T16:35:08.2400210Z       _sockname: null,
2020-06-06T16:35:08.2400338Z       _pendingData: null,
2020-06-06T16:35:08.2400733Z       _pendingEncoding: '',
2020-06-06T16:35:08.2400873Z       server: null,
2020-06-06T16:35:08.2401009Z       _server: null,
2020-06-06T16:35:08.2401121Z       write: [Function: writeAfterFIN],
2020-06-06T16:35:08.2401258Z       [Symbol(asyncId)]: 8,
2020-06-06T16:35:08.2401390Z       [Symbol(kHandle)]: null,
2020-06-06T16:35:08.2401521Z       [Symbol(lastWriteQueueSize)]: 0,
2020-06-06T16:35:08.2401652Z       [Symbol(timeout)]: null,
2020-06-06T16:35:08.2401780Z       [Symbol(kBuffer)]: null,
2020-06-06T16:35:08.2401908Z       [Symbol(kBufferCb)]: null,
2020-06-06T16:35:08.2402038Z       [Symbol(kBufferGen)]: null,
2020-06-06T16:35:08.2402149Z       [Symbol(kBytesRead)]: 947,
2020-06-06T16:35:08.2402279Z       [Symbol(kBytesWritten)]: 0
2020-06-06T16:35:08.2402412Z     },
2020-06-06T16:35:08.2402539Z     stderr: Socket {
2020-06-06T16:35:08.2402666Z       connecting: false,
2020-06-06T16:35:08.2402968Z       _hadError: false,
2020-06-06T16:35:08.2403097Z       _parent: null,
2020-06-06T16:35:08.2403224Z       _host: null,
2020-06-06T16:35:08.2403336Z       _readableState: [ReadableState],
2020-06-06T16:35:08.2403472Z       readable: false,
2020-06-06T16:35:08.2403609Z       _events: [Object: null prototype],
2020-06-06T16:35:08.2403739Z       _eventsCount: 3,
2020-06-06T16:35:08.2403867Z       _maxListeners: undefined,
2020-06-06T16:35:08.2403999Z       _writableState: [WritableState],
2020-06-06T16:35:08.2404129Z       writable: false,
2020-06-06T16:35:08.2404256Z       allowHalfOpen: false,
2020-06-06T16:35:08.2404369Z       _sockname: null,
2020-06-06T16:35:08.2404495Z       _pendingData: null,
2020-06-06T16:35:08.2404824Z       _pendingEncoding: '',
2020-06-06T16:35:08.2404958Z       server: null,
2020-06-06T16:35:08.2405085Z       _server: null,
2020-06-06T16:35:08.2405215Z       write: [Function: writeAfterFIN],
2020-06-06T16:35:08.2405346Z       [Symbol(asyncId)]: 9,
2020-06-06T16:35:08.2405483Z       [Symbol(kHandle)]: null,
2020-06-06T16:35:08.2405593Z       [Symbol(lastWriteQueueSize)]: 0,
2020-06-06T16:35:08.2405723Z       [Symbol(timeout)]: null,
2020-06-06T16:35:08.2405850Z       [Symbol(kBuffer)]: null,
2020-06-06T16:35:08.2406130Z       [Symbol(kBufferCb)]: null,
2020-06-06T16:35:08.2406274Z       [Symbol(kBufferGen)]: null,
2020-06-06T16:35:08.2406402Z       [Symbol(kBytesRead)]: 0,
2020-06-06T16:35:08.2406530Z       [Symbol(kBytesWritten)]: 0
2020-06-06T16:35:08.2406654Z     },
2020-06-06T16:35:08.2406763Z     stdio: [ [Socket], [Socket], [Socket] ]
2020-06-06T16:35:08.2406894Z   },
2020-06-06T16:35:08.2407016Z   stdout: undefined,
2020-06-06T16:35:08.2407144Z   stderr: undefined
2020-06-06T16:35:08.2407267Z }
2020-06-06T16:35:08.2410897Z Could not find directory '/target/surefire-reports'
2020-06-06T16:35:08.2411539Z Could not find directory '/target/failsafe-reports'
2020-06-06T16:35:08.2414486Z { status: 'FAILURE', tests: [], coverage: 0, time: '0.000' }
2020-06-06T16:35:08.2416504Z Preparing Webhook...
2020-06-06T16:35:08.2422401Z Constructing Embed...
2020-06-06T16:35:08.4822494Z Successfully sent the message!
2020-06-06T16:35:08.4901278Z Cleaning up orphan processes
```

**Comment by TheBusyBiscuit** [comment]
`2020-06-06T16:35:08.2048712Z [ERROR] The goal you specified requires a project to execute but there is no POM in this directory (/home/runner/work/-/-). Please verify you invoked Maven from the correct directory. -> [Help 1]`

Hmm, it seems like your Maven build failed in general due to a missing pom.xml
(Also I should pobably fix the log formatting at some point...)

**Comment by thomasbnt** [comment]
owh okay it's for Java projects :sob: 
Too bad, I edit that for remove Tests coverage. I thought it was about GitHub and the builds ^^

**Comment by TheBusyBiscuit** [comment]
Yeah, it currently only supports Maven projects (as stated in the [README](https://github.com/Slimefun/discord-webhook#requirements))

If you really only want a fancier embed, I can of course make it fall back to skipping the build and unit tests altogether and only show the newly added commits.

**Comment by thomasbnt** [comment]
I read it though but the pom.xml didn't jump out at me since I never did java aha xD
I directly wanted to test thinking it was related to GitHub and not to a file ^^
Sorry about that, this is a mistake :octocat:

**Comment by thomasbnt** [comment]
Hello again, how I can delete all tests coverages without bug? 
https://github.com/Slimefun/discord-webhook/blob/master/src/index.js#L21
```js
analysis.start(isSkipped(payload.head_commit)).then((report) => {
        webhook.send(id, token, repository, branch, payload.compare, commits, size, report).catch(err => core.setFailed(err.message));
    }, err => core.setFailed(err));
```
